<?php

/** hook_menu **/
function mqcristobal_misc_menu(){
	$items['mqcristobal-timer'] = array(
		'menu_name' => 'mqc_timer',
		'page callback' => 'mqc_timer',
		'page arguments' => array(1),
		'title' => t('mqc_timer'),
		'access arguments' => array('access content'),
	);
	return $items;
}

/** hook_theme **/
function mqcristobal_misc_theme(){
	$themes = array (
        'mqc_timer' => array(
            'template' => '/templates/mqc-timer', // your template file called custompage.tpl.php
            'variables' => array('args' => NULL),
        ),
    );
    return $themes;
}

function mqc_timer($datetime){
	$params = array(
		'time_remaining' => $datetime - strtotime('now'),
	);
	echo json_encode(array('return'=>theme('mqc_timer', $params)));
}